version: '3'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
     - db
    volumes:
      - ./php:/var/www/html:Z
      - ./logs/apache-access.log:/var/log/apache2/access.log:Z
      - ./logs/apache-error.log:/var/log/apache2/error.log:Z

    ports:
      - 8080:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword 
      MYSQL_DATABASE: test_database
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8183:80
